### ISSUE TITLE
Is there support for conditional multinomial logistic regression?

### ISSUE THREAD

**Issue by rolandkofler** [timothyb0912/pylogit#1]
I wonder if this type of cMNL (the type you use in Choice Based Conjoint/ DCE is supported?

**Comment by timothyb0912** [comment]
Hi rolandkofler,
Could you be more specific about the type of cMNL (any links?) that you are wondering about, or the type of features you are wondering about?

If you're wondering if this package can be used to help design discrete choice experiments, then no this package doesn't have those capabilities. However, PyLogit can estimate conditional logit models after the data from such an experiment has been collected.

If you're wondering about support for features such as individually varying sensitivities (i.e. mixed logit models), they're not yet implemented.
