### ISSUE TITLE
Python 2/3 compatibility for xrange()

### ISSUE THREAD

**Issue by smmaurer** [timothyb0912/pylogit#12]
Hi! I just encountered a small bug using PyLogit on a near-clean install of Anaconda Python 3.6. 

`choice_calcs.py` uses the `xrange()` function, which has been replaced by `range()` in Python 3. To get around this, it tries to import `xrange()` from the future/past library. But Anaconda Python 3 no longer installs future/past by default, so this failed silently. 

https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L575
https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L17-L21

Two easy potential solutions:

1. Add the `future` package to `requirements.txt`

2. Replace `xrange()` with `range()`

The second seems better, but I haven't verified that it will work. I'm happy to take care of this and submit a PR, but in the meantime wanted to write it up in case you've looked into this before!

**Comment by timothyb0912** [comment]
Hey Sam, you're totally right about the potential solutions. I plan on adding the future package to requirements.txt but have been lazy in doing so! Thanks for putting this back on my radar.
