### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by gboeing** [timothyb0912/pylogit#15]
@timothyb0912 would you create a release of your fantastic code commits since last winter? This would make installation much easier, especially for python 3 folks. Latest on pypi dates back to December 2016 and there aren't any releases tagged on GitHub.

**Comment by gboeing** [comment]
BTW do you have any interest in tagging releases on GitHub? It's a really quick and easy way to create official or interim releases:

```
git tag -a v0.1.1 -m "annotation for this release"
git push origin --tags
```

**Comment by timothyb0912** [comment]
@gboeing Yeah, I'll do a release this weekend. And thanks for the info about tagging! I didn't know about it (and clearly haven't used tags, though they seem useful)!

**Comment by gboeing** [comment]
@timothyb0912 thanks!

**Comment by bnaul** [comment]
Any update on the release? :)

**Comment by timothyb0912** [comment]
@gboeing, @bnaul, There's a new release out and the releases have been tagged. I'm closing this for now.

**Comment by gboeing** [comment]
@timothyb0912 you are awesome, thanks!

**Comment by timothyb0912** [comment]
@gboeing: haha, no worries. Sorry it took me so long to get the release out!
