### ISSUE TITLE
Issue when trying to run nested logit example

### ISSUE THREAD

**Issue by pxgo17** [timothyb0912/pylogit#16]
Great package!, thanks for sharing it and for providing very useful examples...I was trying to run the example for nested logit estimation but I am getting this error after I try to fit the model:

ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any 
supported types according to the casting rule ''safe''

These are the calls for the error:

  File "..\lib\site-packages\pylogit\nested_logit.py", line 261, in convenience_calc_log_likelihood
    log_likelihood = general_log_likelihood(*args, **kwargs)
  File "..\lib\site-packages\pylogit\nested_choice_calcs.py", line 317, in calc_nested_log_likelihood
    return_type='long_probs')
  File "..\lib\site-packages\pylogit\nested_choice_calcs.py", line 157, in calc_nested_probs
    inf_idx = np.isposinf(ind_exp_sums_per_nest)
  File "..\lib\site-packages\numpy\lib\ufunclike.py", line 34, in func
    return f(x, out=out, **kwargs)
  File "..\lib\site-packages\numpy\lib\ufunclike.py", line 141, in isposinf
    return nx.logical_and(nx.isinf(x), ~nx.signbit(x), out)

Any ideas of what might be happening? @timothyb0912 @gboeing

**Comment by timothyb0912** [comment]
@pxgo17: Thanks for pointing this out. Basically, what's going on is that https://github.com/timothyb0912/pylogit/blob/master/pylogit/nested_choice_calcs.py#L160 should have evaluated to true and cast the sparse matrix (ind_exp_sums_per_nest) into a regular numpy array. For some reason though, https://github.com/timothyb0912/pylogit/blob/master/pylogit/nested_choice_calcs.py#L161 never executed. I'm not sure why

I'll try to look into this and issue a fix when I have one. Feel free to open up a pull request for this if you get to it before I do.

**Comment by timothyb0912** [comment]
@pxgo17, Try pip or conda installing the latest version of PyLogit. Or if you're working off a clone of the pylogit repo, then do a git pull. There shouldn't be any errors now.

Let me know if you still have any issues.

**Comment by pxgo17** [comment]
Thank you very much!
