### ISSUE TITLE
Feature Request : Regularization

### ISSUE THREAD

**Issue by 26345211** [timothyb0912/pylogit#19]
Not sure if this branches too far from the intended purpose of the packet, is it possible for pylogit to implement L1 or L2 regularization similar to what scikit-learn does.

**Comment by timothyb0912** [comment]
L2 regularization is implemented. See the `ridge` kwarg in all of the `fit_mle` methods.

To see how it is implemented, check out [L285](https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L285) and [L482](https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L482) and [L848](https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L848).
