### ISSUE TITLE
Question about syntax

### ISSUE THREAD

**Issue by samyip123** [timothyb0912/pylogit#20]
The model i am trying to build is predicting the probability of result = 1 given a set of samples, condition being all probi with a set sums to 1 

Data
Result          ID       Attribute_1           Attribute_2
0                    1             0.34                      0.21
1                    1              0.24                      0.11
0                    1            0.13                       0.16
0                    1              0.29                     0.52 
1                    2             0.14                      0.13
0                   2              0.17                     0.08      
0                   2               0.38                   0.51
0                   2               0.31                     0.28

basic_specification_custom = OrderedDict()
basic_specification_custom["Attribute_1"] = [?]
basic_specification_custom["Attribute_2"] = [?]
Choice_Column_custom = "Result"
Obs_Id_Column_custom = "ID"
Model = pylogit.create_choice_model(data=simulation_dataset_train,
                                        alt_id_col=,
                                        obs_id_col=Obs_Id_Column_custom,
                                        choice_col=Choice_Column_custom,
                                        specification=basic_specification_custom,
                                        model_type="MNL")

If the obs_id_col already made sure it starts from 1, what should the alt_id_col and index in the specification dictionary be, thanks

**Comment by timothyb0912** [comment]
@samyip123 For the `alt_id_col` argumnt, you need to add a column to `simulation_dataset_train` that specifies the alternative for each row. For instance, the first four rows seem to specify different alternatives for the decision maker with `ID == 1`. If all decision makers have four alternatives (in the same order), then you might do
```
num_obs = simulation_dataset_train.ID.unique().size
simulation_dataset_train['alt_id'] = np.tile(np.arange(1, 5),  num_obs)
```
You could then have `alt_id_col = "alt_id"` in the function call to pylogit.create_choice_model.

As for what to place in the specification dictionary for attributes 1 and 2, that depends on what you are specifying your model to be. For an examples of how one goes from model specification to the entries in the specification dictionary, see the "Create the model specification" section in the following notebook: https://github.com/timothyb0912/pylogit/blob/master/examples/notebooks/Main%20PyLogit%20Example.ipynb

**Comment by samyip123** [comment]
Could the above model also be used to model a Conditional Logit Model, finding the probability of success with the condition of the probability of success within a  group (same ID) sums to 1. 
<img width="321" alt="screen shot 2018-03-21 at 10 42 21 am" src="https://user-images.githubusercontent.com/37391338/37692574-9019bb6c-2cf4-11e8-880e-d781144e21ac.png">

**Comment by timothyb0912** [comment]
@samyip123 Yep. That is the formula for a conditional logit model, and it is the model that is fit when one uses `model_type='MNL'`.

**Comment by samyip123** [comment]
then what will be the specification dictionary for beta equaling attribute 1 and attribute 2?
