### ISSUE TITLE
Conditional Logistic Regression

### ISSUE THREAD

**Issue by spp020105** [timothyb0912/pylogit#21]
When modeling a conditional logit model with five parameters using the MNL model type, what will be the specification dictionary for those attributes?

**Comment by spp020105** [comment]
for example, a dataset of 100 races and each race has 8 participant and one winner only
I have five parameters which is applicable to all participant 
Race ID	Parti ID	Weight	Height	A	B	C	Result
1		1		70		180		23	23	24	0
1		2		76		175		23	23	24	0
1		3		65		165		23	23	24	0
1		4		54		176		23	23	24	0
1		5		64		183		23	23	24	0
1		6		51		169		23	23	24	1
1		7		69		172		23	23	24	0
1		8		73		173		23	23	24	0
How should I set the specification dictionary this?
I have tried to do `basic_specification_fn = OrderedDict()
basic_specification_fn["Weight"] = [[1,2,3,4,5,6,7,8]]`
but it seems to be incorrect
Can you please help me?

**Comment by timothyb0912** [comment]
@seandickert Thanks for replying and helping out!

@spp020105 The answer by @seandickert is correct. An equivalent alternative is to do
```
spec = OrderedDict()
characteristics = ['Weight', 'Height', 'A', 'B', 'C']
for variable in characteristics:
    spec[variable] = 'all_same'
model = create_choice_model(data,
                            alt_id_col='ID',
                            obs_id_col='Race',
                            choice_col='Result',
                            specification=spec,
                            model_type='MNL')
```

**Comment by seandickert** [comment]
@timothyb0912 that is much better, I wasn't aware of this syntax!  Two questions:

Will this work for varying # of alternatives across observations?

Will this work if we make a prediction on an observation that has a greater number of alternatives than any observation on which we have trained?  I currently hack this by temporarily changing the config spec when I make a prediction

**Comment by timothyb0912** [comment]
The syntax above should work for varying # of alternatives across observations.

If an observation has more alternatives than seen in the training data, then I doubt it'll work. Moreover, I didn't design pylogit with that use case in mind so I am not sure what (else) will break. Feel free to open an issue regarding your use case and hacks you've had to do.
