### ISSUE TITLE
Large Dataset 100,000 groups or about 1,000,000 rows

### ISSUE THREAD

**Issue by csaiedu** [timothyb0912/pylogit#22]
Hi 
Are there any fix implemented to deal with the memory errors when dealing with large datasets?
Thanks

**Comment by timothyb0912** [comment]
Not yet. I'd like to implement an option to use stochastic gradient descent or some mini-batch method to deal with large datasets. I haven't made time to do so, and pull requests would be great here.

**Comment by timothyb0912** [comment]
Closing as essentially a duplicate of [Issue #9](https://github.com/timothyb0912/pylogit/issues/9)
