### ISSUE TITLE
Fitting into an Ensemble

### ISSUE THREAD

**Issue by samyip123** [timothyb0912/pylogit#23]
I am trying to fit the MNL model into an ensemble of classifiers by scikit-learn. 
Is there a way to modify the syntax manually so that is similar to the ones in scikit-learn so it can fit in an ensemble
ie When defining the model (__init__) : pass in the hyperparameters eg : ridge 
And passing the data during the fitting processing instead of the defining process
fit_mle : pass in the Choice_Column, basic_specification, data, sample weight
Is there any wrapper for scikit-learn?
Hope it works because it seems pylogit is the only reliable MNL model for python.

**Comment by timothyb0912** [comment]
Hey @samyip123, I imagine that you can write a wrapper class that mimics the sci-kit learn interface for your ensemble. At the moment, changing pylogit to add a sci-kit learn isn't on the top of my priority list so I may not get to it for a while.

Allowing compatibility with sci-kit learn would be nice though, so if you want to get started on this feature and issue a pull-request when you've got the feature in a good state, please do so!
