### ISSUE TITLE
Feature Request : Frailty

### ISSUE THREAD

**Issue by 26345211** [timothyb0912/pylogit#24]
Not sure if this is already implemented, but does the package include a way to include a Frailty parameter to the likelihood, which simply adds a weight factor to the linear combination of coefficients and parameters.

**Comment by seandickert** [comment]
I don't believe it's available natively. However, you can provide your own implementation of the utility transformation function on the model object returned from create_choice_model, which is what I did personally for the same reason (I'm assuming you're implementing the paper from Dr. Noah Silverman).  You will need to somehow expose the frailty vector that you'd like to use to the pylogit model.  I've done this by writing my own object around pylogit.  So, my function call looks like:

```
def _util_trans(self, systematic_utilities, *args, **kwargs):
    systematic_utilities = systematic_utilities + (self._frailty)
    systematic_utilities = systematic_utilities[:, np.newaxis]
    return systematic_utilities
```

where self._frailty is a vector matching the length of the dataset provided to fit (or predict), and I alter the pylogit model as so:

```
model = pylogit.create_choice_model(...)
model.utility_transform = self._util_trans
```

**Comment by timothyb0912** [comment]
@seandickert thanks for suggesting a solution!

@26345211 another option is as follows. If I'm correctly understanding what the frailty parameter is (from Dr. Silverman's [youtube video](https://youtu.be/5gW0PO7g6pY?t=381)), it's  just a single number for each alternative, e.g. each horse in a horserace.

In that case, you can simply add a frailty term to your dataset and set a constant coefficient of 1 for that parameter. For example:

```
# Let df be one's long-format data.
# Let alt_id_col be the column in df that contains the alternative id's for each row.
# Let frailty_series be a Pandas Series where each index key is an alternative id
# and each value is the frailty term for that alternative
df['frailty'] = df[alt_id_col].map(frailty_series)

# Below, I assume that the specification and name dictionaries
# have already been created with the rest of one's specification
# so the frailty term is the last term in each utility function
specification_dict['frailty'] = 'all_same'
names_dict['frailty'] = 'frailty'

# If one is estimating a conditional logit model as
# Dr. Silverman does, then when estimating the model,
# declare the number of parameters, including the frailty term
# for example I'll use 6
num_params = 6 
initial_values = np.zeros(num_params)
# Make the coefficient of the frailty term = 1
initial_values[-1] = 1
# Constrain the frailty coefficient to equal its initial value, i.e 1
mnl_model.fit_mle(initial_values, ..., constrained_pos=[-1])
```

**Comment by seandickert** [comment]
Yikes - that is so much more sensible than my solution!
