### ISSUE TITLE
Lower memory usage for hessian calculation with large design matrices

### ISSUE THREAD

**Issue by timothyb0912** [timothyb0912/pylogit#25]
# Purpose:
This issue is being opened to centralize and publicize discussion on efforts to reduce the memory usage for the computation of the hessian.

# Problem:
Currently, large memory spikes occur during the hessian calculation if one's design matrix is large. See for example, [Issue 9](https://github.com/timothyb0912/pylogit/issues/9) and [Issue 22](https://github.com/timothyb0912/pylogit/issues/22).

# Root cause:
The problem seems to be caused by the memory allocation for an array `dp_dh` used during the calculation of the hessian. If one's design matrix has shape `(num_rows, num_columns)`, then `dp_dh` has shape `(num_rows, num_rows)`. See [line 734](https://github.com/timothyb0912/pylogit/blob/master/pylogit/choice_calcs.py#L734).

# Helpful information:
For the math of what this matrix is used for, see section 3.3 of the [pylogit computation document](https://github.com/timothyb0912/pylogit/blob/master/documents/pylogit_computation.pdf), especially section 3.3.10. `dp_dh` in the code is the same as `dp_ds` in the document. Apologies in advance for confusion caused by writing the code and writing the document at different times with different notation.

**Comment by timothyb0912** [comment]
# Initial ideas (others welcome!)
1. Switch from using `scipy.linalg.block_diag` to using `scipy.sparse.block_diag` to instantiate `dp_dh`.
2. Switch from creating the hessian through one giant matrix operation to creating the hessian iteratively, in mini-batches.
    a. `b = 1` decision maker at a time
    b. `b > 1` decision makers at a time, where `b` is somehow set based on the amount of memory available.
3. Use automatic differentiation to compute the hessian. This method keeps track of the computations necessary to compute each element of the hessian but otherwise should never instantiate a large matrix like `dp_dh`.
4. Figure out a way to create `dp_dh` and compute operations with it on disk instead of storing it in RAM.

# Pros and Cons
1. Simplest solution, but may only push the scaling problem out to a larger dataset size (perhaps of the sizes commonly seen in industry).
2. May provide a scalable solution for any size dataset, but may become very slow due to the use of a for loop for iteration.
3. Most flexible solution, unlocks many other possibilities for pylogit, and this is likely a scalable solution. However, it is likely to be the most complex solution.
4. Provides a band-aid that may help. This approach may not work for everyone (depending on disk memory available) and it may be very slow due to input/output from writing to disk.

# Notes
Idea 3 is considered complex because it would require the log-likelihood functions to be written in some auto-differentiable function. As far as I know, most auto-differentiation packages either [don't support](https://github.com/HIPS/autograd/issues/80) the use of sparse matrices which pylogit requires or these packages would require pylogit to redefine its model implementations (e.g. pytorch, tensorflow, theano).

**Comment by timothyb0912** [comment]
Shout out to Mustapha Harb from UC Berkeley for the idea.

In Pull #30, I changed PyLogit such that it now never explicitly forms `dP_dS` and instead distributes the matrix multiplications for the hessian across the individual matrices that make up `dP_dS`. These individual matrix multiplications take far less memory and thereby avoid the issues being referenced above, at least for moderately sized datasets (e.g. 20k observations) that used to result in memory errors.

Datasets in the millions may still have problems during estimation but those will be addressed in future issues/pull-requests.

**Comment by seandickert** [comment]
Awesome!  Any idea when this will end up in a release?  I can pull the dev branch to test, but I'm currently using pylogit via pip

**Comment by timothyb0912** [comment]
Hopefully by the end of November. I have one last addition that may take a couple of weeks.
