### ISSUE TITLE
TypeError: invalid type comparison    In[14]: of 'Mlogit Benchmark 2: Kenneth Train's Heating Data'

### ISSUE THREAD

**Issue by LarryLanGH** [timothyb0912/pylogit#26]
Hi Timothy,

Thank you so much for sharing this wonderful package! I'm a freshman about this mixed logit model. I've run this Heating dataset in R successfully. When  I  run the above-mentioned example with Pylogit an error arose at In[14].
I downloaded the 'mlogit_Benchmark--Heating-checkpoint.ipynb' and run  it in the Jupyter notebook of Anaconda3 for Python 3.5. And I just installed Pylogit two days ago by 'conda install -c timothyb0912 pylogit'.  Here is the error information from Jupyter:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-99130abbf1c0> in <module>()
      6                                  specification=model_1_spec,
      7                                  model_type="MNL",
----> 8                                  names=model_1_names)
      9 
     10 # Estimate the given model, starting from a point of all zeros

D:\Program Files\Anaconda3\lib\site-packages\pylogit\pylogit.py in create_choice_model(data, alt_id_col, obs_id_col, choice_col, specification, model_type, intercept_ref_pos, shape_ref_pos, names, intercept_names, shape_names, nest_spec, mixing_id_col, mixing_vars)
    223                                            choice_col,
    224                                            specification,
--> 225                                            **model_kwargs)

D:\Program Files\Anaconda3\lib\site-packages\pylogit\conditional_logit.py in __init__(self, data, alt_id_col, obs_id_col, choice_col, specification, names, *args, **kwargs)
    296                                   specification,
    297                                   names=names,
--> 298                                   model_type=model_type_to_display_name["MNL"])
    299 
    300         # Store the utility transform function

D:\Program Files\Anaconda3\lib\site-packages\pylogit\base_multinomial_cm_v2.py in __init__(self, data, alt_id_col, obs_id_col, choice_col, specification, intercept_ref_pos, shape_ref_pos, names, intercept_names, shape_names, nest_spec, mixing_vars, mixing_id_col, model_type)
    877                                           specification,
    878                                           alt_id_col,
--> 879                                           names=names)
    880 
    881         ##########

D:\Program Files\Anaconda3\lib\site-packages\pylogit\choice_tools.py in create_design_matrix(long_form, specification_dict, alt_id_col, names)
    694                 else:  # the group is an integer
    695                     # Create the variable column
--> 696                     new_col_vals = ((long_form[alt_id_col] == group).values *
    697                                     long_form[variable].values)
    698                     independent_vars.append(new_col_vals)

D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py in wrapper(self, other, axis)
   1281 
   1282             with np.errstate(all='ignore'):
-> 1283                 res = na_op(values, other)
   1284             if is_scalar(res):
   1285                 raise TypeError('Could not compare {typ} type with Series'

D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py in na_op(x, y)
   1167                     result = method(y)
   1168                 if result is NotImplemented:
-> 1169                     raise TypeError("invalid type comparison")
   1170             else:
   1171                 result = op(x, y)

TypeError: invalid type comparison

I also copied and pasted the code to Spyder in Anaconda3. It generated the same error.
Traceback (most recent call last):

  File "<ipython-input-21-6822d6050b7a>", line 1, in <module>
    runfile('C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs/exer_19_03_ML_mixlogit_Pylogit.py', wdir='C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs')

  File "D:\Program Files\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "D:\Program Files\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs/exer_19_03_ML_mixlogit_Pylogit.py", line 147, in <module>
    names=model_1_names)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\pylogit.py", line 225, in create_choice_model
    **model_kwargs)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\conditional_logit.py", line 298, in __init__
    model_type=model_type_to_display_name["MNL"])

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\base_multinomial_cm_v2.py", line 879, in __init__
    names=names)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\choice_tools.py", line 696, in create_design_matrix
    new_col_vals = ((long_form[alt_id_col] == group).values *

  File "D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)

  File "D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")

TypeError: invalid type comparison

Traceback (most recent call last):

  File "<ipython-input-21-6822d6050b7a>", line 1, in <module>
    runfile('C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs/exer_19_03_ML_mixlogit_Pylogit.py', wdir='C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs')

  File "D:\Program Files\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "D:\Program Files\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Larry/Google Drive/CS/Programming_languages/Python/Python programs/exer_19_03_ML_mixlogit_Pylogit.py", line 147, in <module>
    names=model_1_names)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\pylogit.py", line 225, in create_choice_model
    **model_kwargs)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\conditional_logit.py", line 298, in __init__
    model_type=model_type_to_display_name["MNL"])

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\base_multinomial_cm_v2.py", line 879, in __init__
    names=names)

  File "D:\Program Files\Anaconda3\lib\site-packages\pylogit\choice_tools.py", line 696, in create_design_matrix
    new_col_vals = ((long_form[alt_id_col] == group).values *

  File "D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)

  File "D:\Program Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")

TypeError: invalid type comparison

Could you give me some ideas about how to fix it?

Thanks,

Larry

**Comment by LarryLanGH** [comment]
I  noticed that in the results of the .ipynb file posted on your git show Python2.7. What I'm using is Anaconda3 for Python 3.5. Is that the reason to cause this problem?

**Comment by LarryLanGH** [comment]
I tried 'Main PyLogit Example-checkpoint.ipynb' in Jupyter of Anaconda 3 for Python 3.5.  It raised an error at In[12]: # Estimate the multinomial logit model (MNL).  A 'memory  error' raised:

Log-likelihood at zero: -6,964.6630
Initial Log-likelihood: -6,964.6630
D:\Program Files\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:507: RuntimeWarning: Method BFGS does not use Hessian information (hess).
  RuntimeWarning)
Estimation Time for Point Estimation: 0.29 seconds.
Final log-likelihood: -5,159.2583
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-12-edc768a63403> in <module>()
      9 
     10 # Specify the initial values and method for the optimization.
---> 11 swissmetro_mnl.fit_mle(np.zeros(14))
     12 
     13 # Look at the estimation results

D:\Program Files\Anaconda3\lib\site-packages\pylogit\conditional_logit.py in fit_mle(self, init_vals, print_res, method, loss_tol, gradient_tol, maxiter, ridge, constrained_pos, just_point, **kwargs)
    399                                   maxiter,
    400                                   print_res,
--> 401                                   just_point=just_point)
    402 
    403         if not just_point:

D:\Program Files\Anaconda3\lib\site-packages\pylogit\estimation.py in estimate(init_values, estimator, method, loss_tol, gradient_tol, maxiter, print_results, use_hessian, just_point, **kwargs)
    709 
    710         # Calculate and store the post-estimation results
--> 711         results = calc_and_store_post_estimation_results(results, estimator)
    712 
    713     return results

D:\Program Files\Anaconda3\lib\site-packages\pylogit\estimation.py in calc_and_store_post_estimation_results(results_dict, estimator)
    574         estimator.convenience_calc_gradient(final_params)
    575     results_dict["final_hessian"] =\
--> 576         estimator.convenience_calc_hessian(final_params)
    577     results_dict["fisher_info"] =\
    578         estimator.convenience_calc_fisher_approx(final_params)

D:\Program Files\Anaconda3\lib\site-packages\pylogit\estimation.py in convenience_calc_hessian(self, params)
    395                 self.weights]
    396 
--> 397         return cc.calc_hessian(*args)
    398 
    399     def convenience_calc_fisher_approx(self, params):

D:\Program Files\Anaconda3\lib\site-packages\pylogit\choice_calcs.py in calc_hessian(beta, design, alt_IDs, rows_to_obs, rows_to_alts, utility_transform, transform_first_deriv_c, transform_first_deriv_v, transform_deriv_alpha, block_matrix_idxs, intercept_params, shape_params, ridge, weights)
    732     # Note that dp_dh will be a 2D dense numpy array
    733     block_matrices = create_matrix_blocks(long_probs, block_matrix_idxs)
--> 734     dp_dh = block_diag(*block_matrices) * weights[None, :]
    735 
    736     ##########

D:\Program Files\Anaconda3\lib\site-packages\scipy\linalg\special_matrices.py in block_diag(*arrs)
    543     shapes = np.array([a.shape for a in arrs])
    544     out_dtype = np.find_common_type([arr.dtype for arr in arrs], [])
--> 545     out = np.zeros(np.sum(shapes, axis=0), dtype=out_dtype)
    546 
    547     r, c = 0, 0

MemoryError:

**Comment by timothyb0912** [comment]
Hey @LarryLanGH  thanks for pointing this out and for posting the entire error message.

I ran and created the notebooks while using python 2.7 not python 3.x, so it's totally possible there may be issues when using those versions.

While memory issues are a known problem (see [Issue 25](https://github.com/timothyb0912/pylogit/issues/25)), it's a bit weird that the notebooks ran on my laptop using python 2.7 but not on yours when using python 3.5.

Can you create a virtual environment using python 2.7 and see if you can reproduce the errors?

Meanwhile, I'll create an environment with python 3.5 to investigate from my end. I'll respond here afterwards.

**Comment by LarryLanGH** [comment]
Dr. Brathwaite,

Thank you for your email. I'll try to test it in Python 2.7.

Best,

Larry

**Comment by LarryLanGH** [comment]
@timothyb0912 
I installed a virtual environment of Python 2.7 for Jupyter under Anaconda3. Then 'mlogit_Benchmark--Heating-checkpoint.ipynb' can be run successfully in Jupyter Python2  and got exactly the same results shown on Git. It looks like the problem was caused by the different versions of Python2 & 3. My main program which will call Pylogit is in Python 3. So if this package can be adjusted to be suitable for Python 3 too, it would be highly appreciated.
Thanks,
Larry

**Comment by timothyb0912** [comment]
This issue should now be fixed on the `develop` branch of PyLogit, and the update will be pushed to PyPI with the next release. You can get access to the updates earlier by cloning the PyLogit repo and checking out the `develop` branch.

Thanks for pointing out this problem!
