### ISSUE TITLE
Clarification on specification

### ISSUE THREAD

**Issue by georgewambold** [timothyb0912/pylogit#36]
Hey @timothyb0912, thank you for your work on this library!

I'm trying to apply the conditional logit (MNL) model to racing data. I was working through the examples and I don't fully understand what to pass for my `specification` parameter. 

My data is structured like this: 
```
race_id | driver_id | driver_age | attr_a | attr_b | etc.. | was_winner

pl.create_choice_model(
    data       = X,
    alt_id_col = 'driver_id',
    obs_id_col = 'race_id',
    choice_col = 'was_winner',
    specification = ...
)
```
I saw issue #21 , which is a similar question to mine and currently I'm setting my specification like you suggested: 
```
characteristics = ['driver_age', 'attr_a', 'attr_b']
for variable in characteristics:
    spec[variable] = 'all_same'
```
The problem is I don't really understand why I'm setting the `specification` that way. I don't really understand what the `specification` param represents. 

- Am I setting the param properly?

- Is this model the correct type for my problem?

Thanks again for your time writing/maintaining pylogit,
George

**Comment by timothyb0912** [comment]
Hey @georgewambold, thanks for using the package.

For information on what the specification parameter represents, there are two general resources.

First, one can always check the docstring for `pl.create_choice_model` by using `help(pl.create_choice_model)`.

Second, for an example with lots of written explanation and equations for what is going on, check out cell 8 in the [main PyLogit example](https://github.com/timothyb0912/pylogit/blob/master/examples/notebooks/Main%20PyLogit%20Example.ipynb).

I can't really tell from the code snippet you posted whether you're setting the parameter correctly. I would suggest that you check out the notebooks in the examples directory to see how I set the specification parameter.

As for whether the model is the correct type for your problem, I don't ever know if there is a "correct" type of model to be used. I've seen other people use conditional logit models to analyze racing data before, so it's certainly an option with some precedent.

**Comment by timothyb0912** [comment]
@georgewambold Closing this for now if there are no more follow-up questions.

**Comment by georgewambold** [comment]
@timothyb0912 Thanks for addressing my questions! I have my model up and running :) 

As a small side note I saw some other issues that mentioned an SKLearn estimator API for pylogit -- I  can see it would be a large undertaking (due to how SKLearn handles dataframes among other challenges) but I just wanted to let you know that I would also find that API useful 👍 

Thanks again!
