### ISSUE TITLE
Memory error when fitting model

### ISSUE THREAD

**Issue by blistick** [timothyb0912/pylogit#37]
First, thank you so much for creating this wonderful library!

I'm using pylogit for a multinomial logit model that currently, for test purposes, has just four parameters. I can successfully fit the model with up to about 40,000 rows of training data, but when I use 56,000 rows I get a Python memory error (**see below**).

I was previously getting a memory error at about 20,000 rows but switched to the develop branch and saw some improvement. My code looks like this:

```
	model = pl.create_choice_model(trainPD,
		alt_id_col='partid',
		obs_id_col='segmentid',
		choice_col='result',
		specification=spec,
		model_type='MNL')
	model.fit_mle(np.zeros(4)) 
```

Does it seem as if I’m bumping against a known limitation, or is there something else going on? Can you recommend any fix or workaround? My model will eventually have 100+ parameters which I’m assuming will make the memory situation worse.

Thanks in advance for your help.

-Barton Listick

```
Traceback (most recent call last):
  File "model_20.py", line 369, in <module>
    run()
  File "model_20.py", line 256, in run
    model.fit_mle(np.zeros(4))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\conditional_logit.py", line 401, in fit_mle
    just_point=just_point)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\estimation.py", line 707, in estimate
    results = calc_and_store_post_estimation_results(results, estimator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\estimation.py", line 574, in calc_and_store_post_estimation_results
    estimator.convenience_calc_fisher_approx(final_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\estimation.py", line 417, in convenience_calc_fisher_approx
    return cc.calc_fisher_info_matrix(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\choice_calcs.py", line 931, in calc_fisher_info_matrix
    np.max(rows_to_obs.toarray() * weights[:, None], axis=0)
MemoryError
```

**Comment by timothyb0912** [comment]
@blistick thanks for using pylogit!

What you said sounds right. The develop branch should be able to estimate models with larger datasets than the master branch.

The memory issues are known. See for instance Issues #25 and #22. Ideally, one would use some sort of mini-batch optimization algorithm (e.g. stochastic gradient descent) when working with large datasets. I haven't implemented any such thing or modified pylogit to enable use of such optimization routines. Pull requests and member contributions are quite welcome here.

For workarounds, it depends on what you need. If you just want the estimated coefficients and don't care about the usual standard error / p-value info, then you could try passing `just_point=True` to the `model.fit_mle` call.

If uncertainty measures are needed as well, you could try the `just_point` suggestion above followed by using the internal pylogit functions to calculate the hessian manually, then take it's negative inverse to get an estimate of the asymptotic covariance matrix. I'm not certain that calculating the hessian will work with such a large dataset.

**Comment by blistick** [comment]
Thanks for your reply, Timothy!

I really just need the coefficients, so I tried your suggestion of passing just_point=True, but then when I tried to use the model to make predictions I got this error:

```
File "C:\ProgramData\Anaconda3\lib\site-packages\pylogit\base_multinomial_cm_v2.py", line 1897, in predict
    new_index_coefs = self.coefs.values
AttributeError: 'MNL' object has no attribute 'coefs'
```

So it seems that when just_point=True the coefficients are not saved to the model? Any ideas on how to overcome this?

**Comment by timothyb0912** [comment]
yeah, you can do something along the lines of:
```
model_results = model.fit_mle(init_values, just_point=True)
mle_params = model_results['x']
param_list = [mle_params, None, None, None]
predictions = model.predict(prediction_df, param_list=param_list)
```

**Comment by blistick** [comment]
Timothy, your solution worked perfectly! Thank you!
