### ISSUE TITLE
Future Warning

### ISSUE THREAD

**Issue by samyip123** [timothyb0912/pylogit#42]
When implementing the model in python 3.7, numpy 1.16 It encountered the following future warning

//anaconda3/lib/python3.7/site-packages/pylogit/choice_tools.py:703: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  design_matrix = np.hstack((x[:, None] for x in independent_vars))
Log-likelihood at zero: -245.0792
Initial Log-likelihood: -245.0792
//anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py:505: RuntimeWarning: Method BFGS does not use Hessian information (hess).
  RuntimeWarning)
Estimation Time for Point Estimation: 0.02 seconds.
Final log-likelihood: -240.9183

**Comment by timothyb0912** [comment]
Fixed in #58 and in #67 that released the fix to v1.0.0 on PyPI.

Sorry for the delay on this @samyip123.
