### ISSUE TITLE
ImportError: cannot import name 'create_choice_model' in Python 3.x

### ISSUE THREAD

**Issue by sash-ko** [timothyb0912/pylogit#6]
After installation using pip `import pylogit` fails with `ImportError: cannot import name 'create_choice_model'`

**Comment by sash-ko** [comment]
Python version 3.5

**Comment by timothyb0912** [comment]
Hi sash-ko, sorry for the delayed reply. There may be all sorts of errors if one tries to use Python 3. I haven't added support for Python 3.x yet.
