### ISSUE TITLE
Does the package work with outside option?

### ISSUE THREAD

**Issue by neenbum** [timothyb0912/pylogit#82]
I am trying to fit the model with outside (no-purchase) option. In that, I will not have any feature that is available to this outside alternative. Am I able to fit the MNL model using this package?

**Comment by timothyb0912** [comment]
Hi @neenbum, thanks for being patient with my overly delayed reply.
Assuming you have an alternative specific constant / intercept for the no-purchase option, you should be able to fit the MNL model using pylogit.
